### ISSUE TITLE
invalid handshake

### ISSUE THREAD

**Issue by bllchmbrs** [wobsoriano/nuxt-clerk-template#20]
When I do a clean install of this template, it doesn't work.

I get:

```
{"errors":[{"message":"invalid handshake","long_message":"The handshake request is invalid: invalid url scheme","code":"invalid_handshake"}],"clerk_trace_id":"xxxxxxxxxxxxx"}
```
errors.

I have not modified the template at all, I only set the environment variables.

It works when I use `vue-clerk` in a vue app, it's just the nuxt version that is failing.

**Comment by wobsoriano** [comment]
Can you clear your cookies and also make sure to enable the organizations feature in your Clerk dashboard? Thanks!

**Comment by bllchmbrs** [comment]
Done, that worked. Kind of a strange experience because it didn't work incognito either. thanks for your help.
