### ISSUE TITLE
Server middleware in example is misleading

### ISSUE THREAD

**Issue by vancegillies** [wobsoriano/nuxt-clerk-template#4]
In the `/server/middleware/clerk.ts` it file shows passing in runtime values of clerk keys
https://github.com/wobsoriano/nuxt-clerk-template/blob/68b06489820e12724ccfa3be4006d3f881f77512/server/middleware/clerk.ts#L4
This does nothing as `clerk-node-sdk` reads from the environment variables when calling `ClerkExpressWithAuth` which is what is called in `h3-clerk`

**Comment by vancegillies** [comment]
https://github.com/wobsoriano/h3-clerk/pull/3

**Comment by wobsoriano** [comment]
Fixed. Thanks for the PR!
