### ISSUE TITLE
[Question]: Transpilation size and edge support?

### ISSUE THREAD

**Issue by Gerbuuun** [wobsoriano/nuxt-clerk-template#5]
Hi,

I have tried using this with the nitro `vercel-edge` preset.
This does not seem to be supported because I get the following not very descriptive error:
```
TypeError: oM.bind is not a function
    at (index.mjs:1:127692)
    at (__nitro:middleware.js:1:17)
```

Also when transpiling the `vue-clerk` plugin, the entrypoint chunk goes from ~400kB to ~1800kB (not very nice)
Is there a way to not transpile the `vue-clerk` plugin?
Is edge supposed to work?

Also this part gives me a type error but it still works without including it.
```ts
import { withClerkMiddleware } from 'h3-clerk';

export default withClerkMiddleware({
  publishableKey: useRuntimeConfig().public.clerkPublishableKey,
  secretKey: useRuntimeConfig().clerk.secretKey,
});
```
```
Argument of type '{ publishableKey: string; secretKey: string; }' is not assignable to parameter of type 'ClerkMiddlewareOptions | undefined'.
  Object literal may only specify known properties, and 'publishableKey' does not exist in type 'ClerkMiddlewareOptions'.ts(2345)
```

I'm not very knowledgable on this so bear with me :)

**Comment by wobsoriano** [comment]
I'm working on something that should reduce the bundle size - https://github.com/wobsoriano/vue-clerk/pull/5
