### ISSUE TITLE
can't get nuxt useFetch to work on authenticated api routes

### ISSUE THREAD

**Issue by alan-funded** [wobsoriano/nuxt-clerk-template#6]
I have an authenticated route: `/api/v1/customers`

```
import { neon } from '@neondatabase/serverless'
import { drizzle } from 'drizzle-orm/neon-http'
import { customer } from '../../../drizzle/schema'

export default eventHandler(async event => {
  const { auth } = event.context

  if (!auth.userId) {
    setResponseStatus(event, 403)
    return ''
  }

  const connectionString = useRuntimeConfig().neonUrl as string

  const sql = neon(connectionString)
  const db = drizzle(sql)

  const data = await db.select().from(customer)

  setResponseStatus(event, 200)
  return { data }
})
```

And a page.vue that calls it:
```
const { data, error } = await useFetch('/api/v1/customers')
```

I always get 401 on the server side, but it works on the client side.

even if I pass through the headers:
```
const headers = useRequestHeaders()
const { data, error } = await useFetch('/api/v1/customers', { headers })
```

**Comment by wobsoriano** [comment]
and you have a global middleware set up like [this](https://github.com/wobsoriano/nuxt-clerk-template/blob/main/server/middleware/clerk.ts)?

**Comment by alan-funded** [comment]
Yes, working off this repo's code.

BTW the error comes back as:
```
ObjectRefImpl {
  _object: { SWKYoAWNBD: null },
  _key: 'SWKYoAWNBD',
  _defaultValue: undefined,
  __v_isRef: true
}
```

**Comment by alan-funded** [comment]
Would be awesome if `nuxt-clerk-template` had an example of useFetch. Maybe two, one with auth, one without or something.

**Comment by wobsoriano** [comment]
Thanks @alan-funded. Ill look into it

**Comment by wobsoriano** [comment]
Okay, I can confirm this issue. It's caused by this PR https://github.com/wobsoriano/h3-clerk/pull/2 - an infinite reload fix in development.

**Comment by alan-funded** [comment]
Thanks!
Should I wait for a fix or try to screw around with the headers?

**Comment by alan-funded** [comment]
It's slightly different I think. I can pass the headers (tried and did not help), but it just never lands on the API code.
For some reason something in the middleware picks it up earlier, and I get a 401 immediately.

**Comment by wobsoriano** [comment]
You can disable this now with the `adjustProtoHeaderInDev`. See this PR - https://github.com/wobsoriano/h3-clerk/pull/4

**Comment by wobsoriano** [comment]
Looks to be fixed [here](https://github.com/unjs/nitro/commit/29ddd948407322c67aace0336fdc65eed12bad20) but I'm still waiting on the next Nitro release.

**Comment by fredrikburmester** [comment]
@wobsoriano Overwriting nitropack dep with
```
"pnpm": {
    "overrides": {
      "nitropack": "npm:nitropack-nightly@^2.9.0-28437792.77796df"
    }
  }
 ```
  and the issue remains from what i can tell. Are there additional configuration required?

**Comment by wobsoriano** [comment]
@fredrikburmester, this is what I did:

```json
"devDependencies": {
    ...,
    "nuxt": "npm:nuxt-nightly@latest"
}
```

```ts
// server/middleware/clerk.ts
import { withClerkMiddleware } from 'h3-clerk';

export default withClerkMiddleware({
  adjustProtoHeaderInDev: false
});

```

**Comment by wobsoriano** [comment]
This page is using `useFetch` - https://nuxt-clerk-template.vercel.app/profile
