### ISSUE TITLE
[Issue]: I'm getting some type error in Nuxt 3 with this template.

### ISSUE THREAD

**Issue by ohiduzzamansiam1** [wobsoriano/nuxt-clerk-template#9]
```
<script setup lang="ts">
import { useUser } from "vue-clerk";

definePageMeta({
  middleware: ["auth"],
});

const { user } = useUser();
</script>

<template>
  <h1 class="text-3xl font-semibold">👋 Hi, {{ user?.firstName }}!</h1>
  <div class="grid lg:grid-cols-3 gap-4">
    <UserInfo />
    <SessionInfo />
    <OrganizationInfo />
  </div>
</template>
```
In this code the user object's types are correct in the script tag. Like in script tag, if I log user.value?.firstName it works properly and the types are okay. 

But when I use the same type, {{ user.value?.firstName }}, first of all the types doesn't return any kinda error. But when see the output, it is not working. But if I just use {{ user?.firstName }}, although the types throws an error but the outputs work correctly.

The error in template tag but the output works perfectly:
Property 'firstName' does not exist on type 'Ref<undefined> | Ref<null> | Ref<UserResource>'. Property 'firstName' does not exist on type 'Ref<undefined>'.

I'd request you to fix this problem. Beside this, I really appreciate your hard work for others.

Keep love from Bangladesh.💝😊

**Comment by wobsoriano** [comment]
Because refs are automatically unwrapped in templates. Thanks!
